### ISSUE TITLE
catch sleep notifications and pause all GPU slots

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-issues#1006]
| Trac | Data |
| --: | :-- |
| Ticket | 1006 |
| Reported by | @kbernhagen |
| Status | closed |
| Component | FAHClient |
| Priority | 5 |

On Windows, I think the messages are
WM_POWERBROADCAST / PBT_APMSUSPEND
WM_POWERBROADCAST / PBT_APMRESUMEAUTOMATIC

On receiving suspend msg, I propose simply calling
  app.systemWillSleep()

which would
  lock if necessary
  write log message
  slotMgr.systemWillSleep() // set pauseForSleep flag on GPU slots
  slotMgr.update() // or whatever causes an immediate pause
  unlock

For resume, there would be a parallel method
  app.systemDidWake()

For OSX, catching sleep notifications is part of ticket #944.
The systemWillSleep, systemDidWake mechanism would be shared.

**Comment by bb30994** [comment]
Has the problem been solved either in Core_17/_18/_21/_22 or in FAHClient 7.4.xx?
>
The FAHClient setting disable-sleep-when-active was one way to avoid this issue but donors complain that FAH prevents their system from sleeping. If this issue was closed because a better solution was found, then it makes sense to change the default of disable-sleep-when-active to false.

I have not seen any recent reports of WUs being corrupted by a system sleep, but that doesn't prove whether loss of GPU power causes the loss of data from active kernels.

Maybe the FAHCore could suspend issuing new kernels and wait long enough for them all to be returned to main RAM (which will be saved by the OS), but "long enough" is difficult to define.  It's not really necessary to go back to the previous checkpoint as long as all of the data required to resume work is now In main RAM.
