### ISSUE TITLE
FAH availability on older linuxes

### ISSUE THREAD

**Issue by JazzMaster** [FoldingAtHome/fah-issues#1265]
I would advise the multiple tickets on Linux (specifically ubuntu14) to be merged.
The website is pushing for newer RX series radeons. This is half the problem- the 7850, 7990,etc are only supported mostly- under ubunt14 and jessie or below. This was ATI and nvidias WRONG MOVE that will cost you in hardware. This said:
The website points you to v7.5 but older clients are available- if you shortcut the centOS link.
BUG?
debian testing(buster) is 7.4 while debian stable(stretch) is 7.5.

https://download.foldingathome.org/releases/public/release/fahviewer/

**Comment by JazzMaster** [comment]
I did at one point fix the py egg for FAHControl. where it went- I have no clue.

**Comment by JazzMaster** [comment]
confirmed working on 7850 under ubu14. use the 7.4 version. GPU ENABLED for OPENCL with catalyst(not crimson) ATI proprietary drivers. RX only works above hwe enabled 14+(wants 16+) and ubu14.5 release forces hwe mode and kernel 4.x. word to the wise- dig --really dig- for ubu14.2. it does not suffer from the hwe problem. kernel 4.x and X.13(I believe) combined cause the old radeons to stop working.

**Comment by ProDigit** [comment]
I'd recommend to use older GPUs on Windows only, as there are many Linux kernel vulnerabilities been discovered since, and it's not recommend to run any software on older, less supported operating systems.

Ubuntu 14 LTS support ended in April 2019.
While it still receives security updates, the OS will run less and less stable with each security 'patch', as programs aren't updated anymore for these patches.

I recommend to close all tickets for Ubuntu 14 and older.

**Comment by shorttack** [comment]
> I recommend to close all tickets for Ubuntu 14 and older.

The Issues Team will close out tickets from Ubuntu and older.
