### ISSUE TITLE
Upload partial WU option, instead of declare WU Bad upon error.

### ISSUE THREAD

**Issue by ProDigit** [FoldingAtHome/fah-issues#1298]
Instead of uploading a WU as bad, and discarding the processed part, it may be better to allow partial WU upload (until last save state).

Most bad WU's uploaded, are so due to overclocking errors that can happen as far as near to 100% completion.

That way, the entire WU doesn't get declared 'bad'.

**Comment by bb30994** [comment]
FAH functions on the basis of WUs completed, not partial WUs.

I think that  you're forgetting that FAH keeps statistics in two ways.  One as Points and another as the number of WUs you'ge completed.  Each WU is identified with four integers: PRCG.  Either Gen N-1 has been completed or Gen N has been completed.  If you don't upload the completed WU, it doesn't count.

Several years ago, a developmental version of FAH was worked on called a streaming client whereby each checkpoint was uploaded.  It was never rolled out ... partly because they never figured out how to integrate credit for these mini-WUs with the existing points system.  (Yes, there were other serious differences between the existing system and that attempt to work out an alternate way of doing things.)  

That development system was abandoned.

**Comment by shorttack** [comment]
Closed: no action necessary.
