### ISSUE TITLE
Install GROMACS 2019.5

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1308]
The latest version of GROMACS is able to off-load a portion of the CPU calculations to an iGPU.  Since it's common to have and iGPU and FAH does not use it, this would seem to be a worthwhile enhancement to the current FAHCore_a7.

See the documentation for GROMACS 2019 and a discussion here: 
https://foldingforum.org/viewtopic.php?p=310293#p310293
Subject: GROMACS 2019?

**Comment by jefftrull** [comment]
Indeed GROMACS has a number of recent enhancements that could really help FAH throughput, according to them. So much so that the answer to "how can I contribute to GROMACS and help FAH", for them, comes down to "Get FAH to use our latest version". See extensive comments [here](https://mailman-1.sys.kth.se/pipermail/gromacs.org_gmx-developers/2020-March/010717.html).

**Comment by shorttack** [comment]
Closed: request to upgrade to latest Gromacs version.

**Comment by jefftrull** [comment]
Is it an invalid issue? I'm confused about why it was closed.

**Comment by PantherX** [comment]
While they are many optimizations for GROMACS, not all of them are used by F@H. The researchers makes the decision based on how much additional scientific value they can bring to the table VS the current scientific value they have. Adding features for the sake of new features isn't an option.
