### ISSUE TITLE
Windows Server 2016 64Bit

### ISSUE THREAD

**Issue by yasirfaheem** [FoldingAtHome/fah-issues#1355]
The beta version fah-installer_7.6.0_x86.exe and fah-installer_7.6.2_x86.exe do not work on windows server 2016 version 1607 os build 14393.3595. You can install it and at the end of the install it will try to start the service and it can not start it.  I have tried to start the service manually and that does not work either.  
The non-beta version fah-installer_7.5.1_x86.exe works just fine and the service is able to start at the end of the install and I can use the program just like I am used to.
Will, there ever be a 64bit version of Folding@home?

**Comment by shorttack** [comment]
Second question first: the cores are 64-bit using the latest instruction set. The client and control are 32-bit, but that's not a performance penalty.

Beta 7.6 Version issue

[https://foldingathome.org/alternative-downloads/](url) has a single download for Windows and does not restrict Windows Server. Therefore, this issue is a potential defect. This could be an incompatibility with Windows Server and/or a Documentation (restriction required on server version) issue.

**Comment by yasirfaheem** [comment]
fah-installer_7.6.13_x86 works just fine on windows server 2016 version 1607 os build 14393.3595.

**Comment by PantherX** [comment]
Thanks for reporting back! In that case, I shall close this issue :)
