### ISSUE TITLE
Feature request: Create windows 64bit client

### ISSUE THREAD

**Issue by talregev** [FoldingAtHome/fah-issues#1367]
Hi Folding@home team,
Please create windows 64bit client.

**Comment by PantherX** [comment]
Please note that this was initially raised during the development of V7 and since the FahCore_XX which does the actual scientific calculations is 64-bit compatible, there's no need for a 64-bit installer. For details, please see my comment here:
https://github.com/FoldingAtHome/fah-issues/issues/1350#issuecomment-613304739

I will now close this issue :)

**Comment by talregev** [comment]
@PantherX 
Thank you for your answer :)
Even if there isn't real necessary people keep asking about folding@home windows client for 64it.
If it not hard, and even absolute not give any new ability I will recommend just for people will not ask.

**Comment by PantherX** [comment]
I too would like to have a native 64-bit F@H installer but it doesn't justify the overhead for the developers. Maybe this will change in the future, maybe it won't... only time can tell :)
