### ISSUE TITLE
I can't get the beta to run _at all_.  (From #1283)

### ISSUE THREAD

**Issue by shorttack** [FoldingAtHome/fah-issues#1369]
@shorttack Hard to verify that this is fixed in the beta because I can't get the beta to run _at all_.  ... and this is after moving the FAHClient folder to the desktop (because it has "in use files" the uninstaller can't touch), rebooting, manually deleting the FAHClient folder, installing the beta (but NOT starting it), uninstalling the beta (to delete my data directory, just in case), reinstalling the beta...  Trying to open FAHClient or FAHControl from the beta does "nothing" (though something is seemingly running because that whole "in use files" issue mentioned above)

_Originally posted by @ex-nerd in https://github.com/FoldingAtHome/fah-issues/issues/1283#issuecomment-613648803_

**Comment by shorttack** [comment]
> Tried the beta (fahclient-7.6.6-1.x86_64), same result.
@ex-nerd That's not good. Many people are reporting stable. Let's back up: what OS & version? I'm moving this issue to a new case #1369

**Comment by ex-nerd** [comment]
Windows 10 (whatever the latest update is).  I've also been running BOINC (since there are so often gaps in units available for F@H) but eventually managed to get that to stop auto-starting, so it doesn't seem related.

I definitely experienced the same issue as #1370, but think at this point everything is removed:

My workaround for #1370:
* Tried to upgrade, but failed as described
* Tried to move F@H folder recycle bin, but it wouldn't let me due to in-use files
* Moved F@H folder to desktop
* Rebooted
* Deleted F@H folder on desktop
* Was able to then successfully run 7.6.6 installer.
* Clicked "run" and the installer became completely unresponsive (had to force-kill it)
* Decided to reboot again just to be safe.
* Tried to open F@H Control, but nothing (visibly) happened.  Same with F@H Client.
* Decided to reinstall.  Start over from step 1, including issues with in-use files.
* This time, I chose *not* to start F@H, but exited the installer and immediately ran the uninstaller, making sure to check the option to delete "data".
* Reboot (at this point, just trying to eliminate any variables)
* Rerun 7.6.6 installer.  This time, clicking "start" works with no freeze.  Browser opens to client page and it looks like I can run F@H just fine (waited around for units to show up, but didn't get anything).
* Trying to run F@H Client and F@H Manager still has no visible effect.  Once (wasn't able to get it to repeat), F@H Client opened up a terminal and printed some error message but I forgot to take a screenshot and have been unable to replicate.

**Comment by ipkh** [comment]
I tried manually closing processes via TaskManager.  And rebooting.
Still could not install.
After attempting install the link for uninstalling 7.5.1 via Apps & Programs.  It apparently deleted the linked file.

However, I was able to continue using 7.5.1 despite the failed installer routine.

**Comment by walderston** [comment]
I was able to update from 7.5.1 to 7.6.6 without issue. 
Before the installation I ensured the process was killed in Task Manager killing everything that started with FAH
Installed the exe without issue
Opened FAHControl and everything started

**Comment by shorttack** [comment]
Best practice in my experience for Windows for this issue would be:
1. logout and log back in. That kills and restarts the client and any tasks/threads.
2. Uninstall the current version via the Windows Install Panel
3. Install foldingathome to the default directory using express install. That preserves your data.

**Comment by ex-nerd** [comment]
Finally got back around to figuring out what this is.  Turns out I need to right-click and run the apps in administrator mode.   Not what it is about my system that has this requirement, but I assume it's something you want to get fixed before the beta goes live.
