### ISSUE TITLE
FahViewer 7.6.8 beta makes Windows 7 stutter - even without a work unit shown

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-issues#1374]
FahViewer 7.6.8 beta makes Windows 7 stutter - even without a work unit shown.

e.g. writting a text is interrupted for a second often when FahViewer is open in background, even without a work unit shown.

* It is also hard to close the FahViewer window as it does not react on mouse clicks for some seconds.

* On start and close of FahViewer the screen turns black for a second - strange.

Also happens with FahViewer 7.5.1 or 7.4.4.

**Comment by shorttack** [comment]
Please see if you can get support at [https://foldingforum.org/index.php](url). Tell them the OS version, graphics card, RAM and configuration. Your problem sounds like an old PC that's unable to keep up with the demands of the 3D Viewer. Also, we are considering dropping support for Windows 7 going forward since it's unsupported by Microsoft and old.

**Comment by informatorius** [comment]
Certain amount of users still on Windows 7 so I would recommend to not drop it so soon. (Similar to Windows XP which was also still used after EOL)

**Comment by shorttack** [comment]
@informatorius 1. We're pushing more troubleshooting to foldingathome.org as the bandwidth and expertise here is limited. 2. Please publish your FAhViewer.exe set compatibility settings for Windows XP so others can benefit! Thanks.
