### ISSUE TITLE
Chrome problem

### ISSUE THREAD

**Issue by mikenet707** [FoldingAtHome/fah-issues#1401]
Chrome was reset to default settings during/after installation. I lost all my extensions, all my autofill info, and all the icons for my bookmarks. is:issue is:open

**Comment by shorttack** [comment]
Can you please post your log file in the Official Forum: https://foldingforum.org/index.php for the issue to be diagnosed? Foldingathome code does not modify Chrome. The forum can assist you in troubleshooting.

Once the issue is identified and reproducible, an issue will be raised here. GitHub is not used for troubleshooting, the Forum is. -Issue Support-
