### ISSUE TITLE
COVID-19 WUs aborting, backtracking?

### ISSUE THREAD

**Issue by beewus** [FoldingAtHome/fah-issues#1403]
I've been running FAH almost continuously on my Windows 10 machine for over a month doing CPU and CPU WUs with no problems. A few days ago I updated the FAH client to the latest version 7.6.9 to take advantage of its new option to prioritize COVID-19 projects. Since then, I've noticed CPU WUs pausing sometimes for several seconds mid-job, some WUs halting then aborting at 10%, 40%, even 92% completion, and one job I observed even warped its progress percentage from 93% back to 46% before soon after aborting. It feels like about one in ten CPU WUs is failing where before, everything was fine. After a failure, FAH just starts up the next WU if there's one available. GPU WUs continue to run to completion just fine. I'll add that there are no system issues: no hardware changes, power and heat levels are fine, network connection is fine, abundant storage and RAM, etc. Also, my machine is able to get through CPU jobs estimated to take 7 day in a couple of hours, so there's no time expiry happening. Thoughts?

**Comment by shorttack** [comment]
1. Can you please post your log file in the Official Forum: https://foldingforum.org/index.php for the issue to be diagnosed? There's not enough information provided. Once the issue is identified and reproducible, an issue will be raised here. GitHub is not used for troubleshooting, the Forum is. 
2. 7.6.10 fixed some GPU problems. Find it at [https://foldingathome.org/beta/](url)

> my machine is able to get through CPU jobs estimated to take 7 day in a couple of hours, so there's no time expiry happening. Thoughts?
3. A work unit has to progress a percent or more before the ETA clock is reasonably accurate.

> CPU WUs pausing sometimes for several seconds mid-job
4. Periodic checkpoints can slow down processing. You control how often checkpoints happen (default 15 minutes.)
