### ISSUE TITLE
FAHClient Webserver binds only to 127.0.0.1

### ISSUE THREAD

**Issue by uklatt** [FoldingAtHome/fah-issues#1405]
I want to reach the FAHClient Webserver from another machine in my local network.
This seems to be not possible becaues the internal webserver offers its service onbly at 127.0.0.1

I tried to bind it to another IP without success.
I got allways the error message "401 HTTP UNAUTORIZED /"

Uwe

**Comment by shorttack** [comment]
Can you please post your log file in the Official Forum: https://foldingforum.org/index.php for the issue to be diagnosed? Once the issue is identified and reproducible, an issue will be raised here. GitHub is not used for troubleshooting, the Forum is. -Issue Support-

Many folders use [https://github.com/harlam357/hfm-net](url) for remote monitoring and control. You can also find hfm.net users on foldingforum.org.

Closed: not an error
