### ISSUE TITLE
My Gpu is not using FAH 

### ISSUE THREAD

**Issue by StaRkBlaCkCoDeR** [FoldingAtHome/fah-issues#1435]
I have Gtx1050 GPU in my laptop but it's not using while in FAH

**Comment by HK0811** [comment]
Hi. I also have this problem before. Someone in the F@H Discord have me this link. All the instructions are in the link.
 []()https://foldingforum.org/viewtopic.php?p=328592#p328592 (it's a known bug in v7.6.8 and 7.6.9)

**Comment by PantherX** [comment]
Please note that while this was a bug, it has been fixed in the latest beta. Thus, I will close this issue now :)

If you require further assistance, please hop over to the Official Forum https://foldingforum.org/index.php for troubleshooting. GitHub is generally used to document reproducible issues which allows the developers to triage and focus their efforts.
