### ISSUE TITLE
"Light" Mode of FAH is a lie....

### ISSUE THREAD

**Issue by crax2max** [FoldingAtHome/fah-issues#1451]
Have a look at attached screenshot with nothing else running....

![FAH_CPU_USAGE_LIGHT](https://user-images.githubusercontent.com/36172801/80892690-098dfb80-8cc4-11ea-8083-8f8dd2a407c1.jpg)

I am happy to run this app, in background while I am working, but having so many cores runing at 70% is NOT light.

**Comment by PantherX** [comment]
Please note that currently this issue is not a report of a problem. I would suggest that you head over to the Official Forum: https://foldingforum.org/index.php where you can discuss what "light" means with respect to folding and if you provide your definition of "light" I am sure that the forum members would be more than happy to help you out.

We prefer to use GitHub to track issues that are well defined and reproducible to allow the development team to triage. The Forum is for everything else :)

**Comment by crax2max** [comment]
I disagree if some software says one but software does another this is
clearly a bug!

Please reopen

**Comment by bb30994** [comment]
The slider gives you only three choices which have to work no matter what hardware features you happen to have.  For most people, there are a lot more choices that cannot be selected with the power slider although you can adjust them using FAHControl.  Please make use of the choices you have there.

Suggested enhancements to the slider are unlikely to be incorporated when there's already a way to accomplish what you're really wanting to do.
