### ISSUE TITLE
Dialog Box opened from FahCore22.exe, entry point clReleaseDevice could not be located

### ISSUE THREAD

**Issue by lurklad** [FoldingAtHome/fah-issues#1490]
## Environment 
* OS: Windows 7 Enterprise 64 build 7601 SP1
* FAH version: April 28, 2020

## What were you trying to do
Folding on FAH for Covid-19

## What happened
NVIDIA GEOFORCE GT 610 as GPU:0 hangs, throws dialog box, FahCore_22.exe - Entry Point Not Found. White X in Red circle: The procedure entry point clReleaseDevice could not be located in the dynamic link library OpenCL.dll.  "OK" the dialog box, and a second box is thrown of same type
 OK that one and GPU process indicator turns to solid yellow. And this cycle continues over and over.
## To Reproduce
just keeps happening each time.

**Comment by lurklad** [comment]
![folderror](https://user-images.githubusercontent.com/65559379/82241411-1ccad900-990a-11ea-9bc1-2e06c6d405cb.jpg)

**Comment by PantherX** [comment]
Please note that for troubleshooting issues, pop-over to the Official Forum (https://foldingforum.org/index.php). There are lots of Donors willing to help you out. We prefer to use GitHub for documented bugs and planned feature. Since this is neither, I will close it :)

PS. To successfully fold on Windows, you will need to have the latest drivers from Nividia which includes CUDA and OpenCL. Drivers from Microsoft/Windows update will not have them.

**Comment by lurklad** [comment]
PantherX, I do not accept closure of this defect I reported. I spent plenty of time on the forums looking for a solution and did a clean install of the NVIDIA drivers from their site prior to entering the defect. If you have a specific version of this dll that you want used with your folding app, then you should specify what that versions should be and let me know what it is. I had planned on devoting this computer to folding for your projects, but if you can't take the time to solve your problems, then goodbye! BTW, I am a seasoned SW Dev. Engineer retired from a top R&D company, with as many years experience with defect tracking. I find your reply unacceptable.

**Comment by PantherX** [comment]
Apologies if I came across as rude... that's wasn't my intention and will never be.

In your original report, you didn't mention that you already visited the Forum. I can't know what isn't explicitly stated... I can't read minds, just English text that is stated in the issue :)

The reason we recommend to head to the Forum for any troubleshooting or issues you encounter is because there's a single developer (not me) who is responsible for all the software development for F@H Project. That's a massive amount of code base to look after. Everyone else here are volunteers who support the F@H Project. The Forum has lots of more volunteers and can provide a faster response to your issue. It's a win-win situation where you get the answers/guidance to your issue ASAP and there's less overhead here for the development team to manage.

Please note that you're running Windows 7 which is no longer supported by Microsoft (https://support.microsoft.com/en-nz/help/4057281/windows-7-support-ended-on-january-14-2020) the development team will not consider support for OS that is deprecated :(

Regarding the specific OpenCL issue, we have always followed Nvidia's guidelines of installing the latest driver. Can you confirm that you have installed Nvidia Driver 391.35 WHQL from here on your system (https://www.nvidia.com/Download/driverResults.aspx/132838/en-us)? If you have, then it seems that you will be unable to fold on GPU in Windows 7 due to the OS limitation.

You can proceed ahead with 2 options:

1. CPU folding - You can continue to run Windows 7, remove the GPU slot and simply leave the CPU slot to fold.
2. OS Change - You can install *inux (common options are Ubuntu/Mint), install the Nvidia driver (closed-source), install OpenCL package and try to fold on the GPU and CPU.

**Comment by bb30994** [comment]
Please return to  foldingforum.org,
As was asked there:  Did you download your drivers directly from NVidia.com? 
... and did you do a clean install?

**Comment by bb30994** [comment]
What version of OpenCL is installed?  I believe this entry point was added in v 1.2
