### ISSUE TITLE
New work units are not started on GPU when monitor is disconnected

### ISSUE THREAD

**Issue by sullivanmj** [FoldingAtHome/fah-issues#1509]
## Your Environment
* **F@H Software version**: 7.5.1
* **Operating System**: Windows 10 Pro Update 1909, build 18363.836
* **Browser**: Internet Explorer 11.836.18362.0
* **GPU**: https://www.asus.com/us/Graphics-Cards/ROG-STRIX-RX570-O4G-GAMING/overview/

----
## Expected Behavior
FAH should use the GPU for folding, even when no monitor is connected.

----
## Current Behavior
FAH does not start new work units on the GPU when there is not a monitor connected to it. I either have to plug it in, or create a remote desktop session to the machine, to get a new work unit to start on the GPU. Work units that were started when a monitor was connected, and then unplugged, **do**, however, appear to run to completion.

----
## Steps To Reproduce
1. Use Folding At Home.
2. Set the client settings to "Any Disease", "Full" Power, and "While I'm working".
3. Unplug the monitor from the GPU.
4. Wait for several hours. Note that the CPU will be used to process new work units, but the GPU will not start any new work units until a monitor is plugged in, or a remote desktop session is created.
5. You can continually verify this, by waiting several hours (past the duration when a work unit would have completed on the GPU), and selecting a random time to log into the machine via remote desktop. You will see that the GPU's work unit (if available) will always be starting at 0%.

----
## Context

I do not always have a monitor plugged into the machine that I use FAH on, but it has a somewhat powerful GPU that I would like to leverage. Especially, since, the times that the monitor is not plugged in, the machine is not in use.

----

**Comment by PantherX** [comment]
Hiya @sullivanmj 
Thanks for your report. Please note that V7 does support folding on the GPU in a headless manner (no input nor dummy plug required) for several years.

The latest version of the client is V7.6.13 so may I suggest that you update it. You can also consider to check the power settings and use the latest version of the drivers. If you need further assistance, please feel free to post in the Official Forum (https://foldingforum.org/index.php) where there are several knowledgeable members who would be willing to help you troubleshoot your issue.

Please note that since this isn't an issue, I will close it now :smiley:
