### ISSUE TITLE
No Points Awarded

### ISSUE THREAD

**Issue by chordlines** [FoldingAtHome/fah-issues#1510]
![image](https://user-images.githubusercontent.com/66259032/83414355-f6fe0380-a3e2-11ea-8a68-b474043e7a4c.png)

I have been Running for hours now and have received any points.

**Comment by PantherX** [comment]
Please note that it is a known cosmetic issue: https://foldingforum.org/viewtopic.php?f=16&t=35430

I will close this issue now since this isn't a new issue. For further troubleshooting, please use the Forum as GitHub is meant for documented issues for the development team.

P.S. Please use the template since it ensure that triaging issues is a lot easier for the volunteers who look after this. Issues not using the template might be closed without any consideration in future.
