### ISSUE TITLE
Lost all the progress on the work 

### ISSUE THREAD

**Issue by nitinjain2605** [FoldingAtHome/fah-issues#1511]
After my laptop restarted, the Folding App crashed a few times and then I lost all the work progress which was done for a work unit. I am folding as nitinjain26.

**Comment by PantherX** [comment]
Please note that we would like you to use the Official Forum (https://foldingforum.org/index.php) for troubleshooting issues. We tend to use GitHub for documented issues for the Development Team to work on.

P.S. Please use the template provided when reporting issues. It makes it easier for volunteers managing GitHub due to consistency. Not using templates might result in issues being closed without any consideration.
