### ISSUE TITLE
Points stuck at zero

### ISSUE THREAD

**Issue by epiclinus360** [FoldingAtHome/fah-issues#1513]
## Your Environment

* **F@H Software version**: 7.6.9
* **Operating System**: Windows 10 64 Bit
* **Browser**: Chrome 83.0.4103.61

----
## Expected Behavior

Showed my points

----
## Current Behavior

It changed to zero after adding a passkey while folding and after 2 more completed folds it is still stuck at zero

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1. Adding passkey during fold
2. Check points after another fold
3. Points at zero

----
## Context

It has not affected me much, I was just folding and thought it was weird.

----

**Comment by PantherX** [comment]
Hiya @epiclinus360 
Please note that the Web Control would show you the points accumulated by the passkey and username. It will ignore any points credited without the passkey.
Also, there's a known issue with the Stats system: https://foldingforum.org/viewtopic.php?f=16&t=35430

Since this isn't an issue, I will close it but if you need further help, please head over to the Forums :)

PS. The latest version is V7.6.13 so you may want to consider updating it: https://foldingforum.org/viewtopic.php?f=24&t=34466
