### ISSUE TITLE
fahviewer_7.6.13_amd64.deb bug

### ISSUE THREAD

**Issue by CynicalMexican** [FoldingAtHome/fah-issues#1516]
I'm operating a 2019 kali linux os (debian) and installing this package (fahviewer_7.6.13_amd64.deb) is not working. I can open the installer and it can recognize the software but hitting install does absolutely nothing. The progress bar opens says 0% then immediately refreshes and the install button reappears. This might just be my mistakes or something on my end but it's worth checking out. Thanks if you have any suggestions solving this issue.

**Comment by PantherX** [comment]
Hiya @CynicalMexican 
May I please suggest that you head over to the Official Forum (https://foldingforum.org/index.php) for troubleshooting. There are many members there to help you investigate.

We tend to use GitHub for documented issues for the development team to resolve. I will close this issue now as it isn't fully documented and needs to be investigated first.

P.S. In future, please use the provided template for reporting issues. It makes it easy for the volunteers to triage issues. In future, issues not using the template might not be considered.

**Comment by ejoepan1** [comment]
PantherX

I see you closing a lot of issues in GitHub referring the creator of the issue to the Forum rather than to GitHub.

If you look at the Help section of the Webclient (shown below) you will see that folks are directed to GitHub to report Bugs.

Clearly the process is different and it should be correctly stated on the help page of the webclient so you don’t have to keep closing the issues on GitHub.

Joe

[A screenshot of a cell phone  Description automatically generated]

**Comment by PantherX** [comment]
@ejoepan1 
Thanks for that! I have created an enhancement request here: https://github.com/FoldingAtHome/fah-issues/issues/1518

**Comment by ejoepan1** [comment]
I saw that and think it is worded well. Good Job!!
