### ISSUE TITLE
2 Instances, same name, same passkey not amalgamated reults

### ISSUE THREAD

**Issue by IanBlakeley** [FoldingAtHome/fah-issues#1517]
For some time I have the SW running on Linux MINT, I have a passkey and my stats are being added to team 47957. I just installed another instance on my Windows 10 laptop used the same email and same passkey.

I thought this should mean that the work from the 2 clients is combined.

Looking at the team stats I see myself twice, the original updates when the Linux machine is running and it appears the newer one is from the Windows machine.

It is not of great importance. I believed the point of the passkey was so that there would not be multiple instances of the same person/email

**Comment by ffissore** [comment]
(edited so that the font doesn't shout)

**Comment by PantherX** [comment]
Hiya @IanBlakeley 
Please note that as long as the exact username/passkey are used on multiple systems, there should be a single identity on F@H. However, usernames are not unique so there could be another donor could be folding with the same username.

If you would like further assistance, please head over to the Official Forum (https://foldingforum.org/index.php) where there are several Members who can assist you further if needed.

Since this isn't an issue, I will be closing this issue now. We tend to use GitHub for documented issues for the development team and the Forums for troubleshooting.
