### ISSUE TITLE
Points not accurately reflecting

### ISSUE THREAD

**Issue by JeremyD130** [FoldingAtHome/fah-issues#1550]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 7.6.13
* **Operating System**: MacOS Catalina 10.15.6
* **Browser**: Safari and/or Chrome

----
## Expected Behavior

Points should update on internet application.

----
## Current Behavior

I started up F@H on my MacBook Pro after finally fixing a broken fan. When I load the internet dashboard, the points are not accurate there, but are accurate on my other computer and on the F@H server. Is there a delay with updating the stats when the application hasn't been used in a bit?

----
## Possible Solution (Optional)

Delay anywhere? I cleared all internet history but still inaccurate (showing 17M instead of 58M)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

I'd like to make sure everything is accurate with my donor name (it's correct!)
<img width="931" alt="Screen Shot 2020-08-14 at 1 23 17 PM" src="https://user-images.githubusercontent.com/69696291/90289757-68b9eb00-de31-11ea-84d7-c52a2d0d8194.png">

----

**Comment by Florian-249** [comment]
I have the same problem. I started runnung FAH on a second netbook and the points aren't added to mine. I checked the name, team-number, passkey. Everything is the same.

**Comment by PantherX** [comment]
Hiya @JeremyD130 & @Florian-249 
Thanks for reporting your findings. Please bear with me while I explain why this isn't an issue.

Within the F@H system, usernames are not unique. Thus, the information you see in the official stats (https://stats.foldingathome.org/donors) will include all points for that username.

F@H later introduced the concept of passkey (https://foldingathome.org/support/faq/points/passkey/) which is unique to the combination of username and email address (username is case sensitive).

The client will show stats based on the following information:

- If no passkey is entered: username (may or may not include team number depending on the client configuration)
- If passkey is entered: username plus passkey

Thus, that would explain the discrepancy you are seeing. For donors who have been contributing prior to the passkey, the difference can be in the millions and unfortunately, there's nothing that can be done since a WU that has been credited with a particular combination of username/passkey/team will not be changed. It is virtually immutable. The only exception is if a username is found to be cheating, the points will be deleted.

Thus, I will close your issue now. If you would like to discuss this further, please head over to the Official Forum (https://foldingforum.org/index.php) 😃

**Comment by JeremyD130** [comment]
I was able to figure it out!! I have to not only uninstall FAH from the
laptop, but had to do a deep dive to remove two more files that were
retaining the incorrect info. Once I did that and reinstalled - I was
completely synced!! Nothing to do with passkey or team or anything like
that :)

**Comment by PantherX** [comment]
Glad that you sorted it out, @JeremyD130! That's interesting since the client doesn't cache any information about user stats AFAIK. It could be the config.xml which might have the incorrect information stored in it due to a typo 🤔

**Comment by JeremyD130** [comment]
Me too!! I'd definitely recommend having people with the same issue 
doing the same going forward as that couldn't have been easier. The 
uninstall leaves those remnants so we'll direct users to delete them as 
well...couldn't have been easier once I knew what to look for!

------ Original Message ------

**Comment by PantherX** [comment]
Okay, to confirm, you had config.xml file saved in C:\Users\<username>\AppData\Roaming\FAHClient and after deleting it, everything worked fine?

Can you also confirm that during the uninstallation process, you selected the option to delete data?
