### ISSUE TITLE
Beta Client 7.6.17 can't detect OpenCL

### ISSUE THREAD

**Issue by ipkh** [FoldingAtHome/fah-issues#1555]
I installed client 7.6.17 on both Windows 10 and Xubuntu 20.10.  In both cases the GPU slots fail with an error in the log about finding a GPU with OpenCL1.2+.
It does immediately fold properly when 7.6.13 is reinstalled.

**Comment by Stan-Dm** [comment]
Same problem here. fah-installer_7.6.17_x86 fails to use GPU on my NVIDIA card.
GPU: GIGABYTE GeForce RTX 2080 SUPER WINDFORCE OC 8G, model # GV-N208SWF3OC-8GD
GPU driver: 452.06-desktop-win7-64bit-international-whql.exe
OS: Win7 x64

fah-installer_7.6.13_x86 works perfectly fine

**Comment by PantherX** [comment]
Hiya @ipkh & @Stan-Dm 
Please note that the client version available on the Beta page is currently only for developers to test and report back. This is a known issue since last month and will be addressed in the next developmental version. Until a public Beta is announced, it would be nice to avoid using any of those builds.

Please note that I will close this issue now since V7.6.17 was never meant to be used by the public. The latest stable version is V7.6.13 and the next Beta version is yet to be determined 😄

**Comment by ipkh** [comment]
The website should have some wording to note the intended audience of beta clients. 
Currently it seems to invite use and feedback.

**Comment by PantherX** [comment]
I do understand your POV and agree with it, @ipkh since it seems that the medium to distribute the developmental build (public Website) might not have been the correct one. There is an on-going discussion where the developmental builds will be posted to a non-public site and then the Public Beta will be available on the website which we would encourage to test and report 😄
