### ISSUE TITLE
Installed in new computer and just sits at "Ready"

### ISSUE THREAD

**Issue by MiloatHome** [FoldingAtHome/fah-issues#1564]
I had to replace a hard drive and after reinstalling the FAHClient and relaunching the browser, it just sits idle by "Ready". 

User is MLMilo if needed.

**Comment by PantherX** [comment]
Hiya @MiloatHome 
Please note that we use GitHub for documented issues. It seems that you might have a troubleshooting issue in which case, we would defer you to our Official Support Forum: https://foldingforum.org/index.php where many knowledgeable members are there to help you out.
Since this isn't an issue, I will close this now 😄
