### ISSUE TITLE
F@H does not deploy correct project for solver inspite of "research" selection from drop down menu.

### ISSUE THREAD

**Issue by nilayksrivastava** [FoldingAtHome/fah-issues#1592]
Folding at home does not seem to be choosing the right projects for solvers inspite of selecting clearly from the drop down menu. the kind of research I'm interested in supporting.
![image](https://user-images.githubusercontent.com/50041640/99191437-b6006e00-273a-11eb-8fff-b9b3b19084c7.png)

**Comment by PantherX** [comment]
Hiya @nilayksrivastava 

Please note that the preference of COVID-19 is just that... a preference and if WUs from your preference aren't available, you will be assigned a WU that best matches your hardware. This is a design feature. Hopefully, this answers your question.

Since this isn't a bug, I will be closing this issue. If you would to discuss this further, you can head over to our official Forum (https://foldingforum.org/index.php) 😄
