### ISSUE TITLE
Completed WU not attributed

### ISSUE THREAD

**Issue by NicoleRauch** [FoldingAtHome/fah-issues#1612]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 7.6.21
* **Operating System**: MacOS 10.15.7
* **Browser**: Firefox 83.0

----
## Expected Behavior

I completed a WU and I expected the points to be attributed to my account.

----
## Current Behavior

The points from the completed WU did not get attributed to my account.
(Does that also mean my work was lost? That would be even worse.)

Here is the relevant part of the log which describes the completion of the WU in question:

```
00:08:35:WU01:FS00:0xa7:Completed 495000 out of 500000 steps (99%)
00:10:27:WU01:FS00:0xa7:Completed 500000 out of 500000 steps (100%)
00:10:35:WU01:FS00:0xa7:Saving result file ../logfile_01.txt
00:10:35:WU01:FS00:0xa7:Saving result file frame33.trr
00:10:35:WU01:FS00:0xa7:Saving result file md.log
00:10:35:WU01:FS00:0xa7:Saving result file science.log
00:10:35:WU01:FS00:0xa7:Saving result file traj_comp.xtc
00:10:35:WU01:FS00:0xa7:Folding@home Core Shutdown: FINISHED_UNIT
00:10:36:WU01:FS00:FahCore returned: FINISHED_UNIT (100 = 0x64)
00:10:36:WU01:FS00:Sending unit results: id:01 state:SEND error:NO_ERROR project:16927 run:15 clone:827 gen:33
 core:0xa7 unit:0x0000033b000000210000421f0000000f
00:10:36:WU01:FS00:Uploading 6.31MiB to 129.32.209.201
00:10:36:WU01:FS00:Connecting to 129.32.209.201:8080
00:10:43:WU01:FS00:Upload 12.87%
00:10:50:WU01:FS00:Upload 34.66%
00:10:56:WU01:FS00:Upload 36.64%
00:11:02:WU01:FS00:Upload 38.62%
00:11:08:WU01:FS00:Upload 39.61%
00:11:16:WU01:FS00:Upload 42.58%
00:11:23:WU01:FS00:Upload 43.57%
00:11:31:WU01:FS00:Upload 45.56%
00:11:42:WU01:FS00:Upload 47.54%
00:11:51:WU01:FS00:Upload 49.52%
00:11:57:WU01:FS00:Upload 51.50%
00:12:04:WU01:FS00:Upload 54.47%
00:12:12:WU01:FS00:Upload 56.45%
00:12:18:WU01:FS00:Upload 67.34%
00:12:24:WU01:FS00:Upload 79.23%
00:12:30:WU01:FS00:Upload 95.07%
00:12:34:WU01:FS00:Upload complete
00:12:34:WU01:FS00:Server responded WORK_ACK (400)
00:12:34:WU01:FS00:Final credit estimate, 13263.00 points
00:12:34:WU01:FS00:Cleaning up
******************************* Date: 2020-12-31 *******************************
08:25:11:4976:127.0.0.1:New Web session
```
(Explanation: I set the client to stop after having finished the WU, and in the morning I resumed it manually.)

But the "Recent CPUs" page only lists the previous WU:

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/436499/103404011-6cd17580-4b52-11eb-91dc-226cb8145403.png">

As you can see, "Last returned" is 20:35 on the 30th and not 0:12 on the 31st, as I would have expected from the above log.

----
## Steps To Reproduce

No idea tbh :-(

I'm pretty sure the same glitch happened to me the day before that, but I did not trace it in the logs as I thought that maybe I was confused. It seems to happen only on the larger WUs, though (they were both >10,000 points on my machine). I processed a few smaller WUs in between which went fine.

----

**Comment by NicoleRauch** [comment]
It just happened again...

Here is a screenshot that I took while my machine was on that WU:

![Bildschirmfoto 2020-12-31 um 18 26 01](https://user-images.githubusercontent.com/436499/103422220-9adda680-4ba0-11eb-907b-37c48a2dd895.png)

Here is the excerpt from the log around the time when that WU was finished and uploaded:

```
17:32:49:WU00:FS00:0xa7:Completed 480000 out of 500000 steps (96%)
17:35:48:WU00:FS00:0xa7:Completed 485000 out of 500000 steps (97%)
17:39:15:WU00:FS00:0xa7:Completed 490000 out of 500000 steps (98%)
17:42:39:WU00:FS00:0xa7:Completed 495000 out of 500000 steps (99%)
17:42:40:WU01:FS00:Connecting to assign1.foldingathome.org:80
17:42:40:WU01:FS00:Assigned to work server 128.252.203.10
17:42:40:WU01:FS00:Requesting new work unit for slot 00: cpu:16 from 128.252.203.10
17:42:40:WU01:FS00:Connecting to 128.252.203.10:8080
17:42:41:WU01:FS00:Downloading 2.07MiB
17:42:42:WU01:FS00:Download complete
17:42:42:WU01:FS00:Received Unit: id:01 state:DOWNLOAD error:NO_ERROR project:17217 run:711 clone:4 gen:46 cor
e:0xa7 unit:0x000000040000002e00004341000002c7
17:46:10:WU00:FS00:0xa7:Completed 500000 out of 500000 steps (100%)
17:46:31:WU00:FS00:0xa7:Saving result file ../logfile_01.txt
17:46:31:WU00:FS00:0xa7:Saving result file frame26.trr
17:46:31:WU00:FS00:0xa7:Saving result file md.log
17:46:31:WU00:FS00:0xa7:Saving result file science.log
17:46:31:WU00:FS00:0xa7:Saving result file traj_comp.xtc
17:46:31:WU00:FS00:0xa7:Folding@home Core Shutdown: FINISHED_UNIT
17:46:31:WU00:FS00:FahCore returned: FINISHED_UNIT (100 = 0x64)
17:46:31:WU00:FS00:Sending unit results: id:00 state:SEND error:NO_ERROR project:16927 run:13 clone:920 gen:26
 core:0xa7 unit:0x000003980000001a0000421f0000000d
17:46:31:WU00:FS00:Uploading 6.30MiB to 129.32.209.201
17:46:31:WU00:FS00:Connecting to 129.32.209.201:8080
17:46:31:WU01:FS00:Starting
17:46:31:WU01:FS00:Running FahCore: /usr/local/bin/FAHCoreWrapper "/Library/Application Support/FAHClient/core
s/cores.foldingathome.org/osx/64bit-avx-256/a7-0.0.19/Core_a7.fah/FahCore_a7" -dir 01 -suffix 01 -version 706 
-lifeline 30392 -checkpoint 15 -np 16
17:46:31:WU01:FS00:Started FahCore on PID 52795
17:46:32:WU01:FS00:Core PID:52796
17:46:32:WU01:FS00:FahCore 0xa7 started
```

Here is a screenshot from the Recent CPUs page that shows no attribution of that WU:

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/436499/103422252-c791be00-4ba0-11eb-968d-61d95f5a6797.png">

---

Any ideas? I think I will suspend working on FAH for the time being because it does not make sense to me as long as I don't know where the folding results end up... Thanks in advance for any insights!

**Comment by PantherX** [comment]
Hiya @NicoleRauch 

Regarding your first WU, the correct people are already notified and work is underway to resolve the missing stats. Unknown ETA due to seasonal break.

Regarding your second WU, it has been credited and you can check the status here: https://apps.foldingathome.org/wu#project=17217&run=711&clone=4&gen=46
I would personally suggest that you use the WU Status Web App (https://apps.foldingathome.org/wu) instead of the recent CPUs App as it provides a more accurate picture.

BTW, if you do encounter missing WU credits but the log file shows this:
```
00:12:34:WU01:FS00:Upload complete
00:12:34:WU01:FS00:Server responded WORK_ACK (400)
00:12:34:WU01:FS00:Final credit estimate, 13263.00 points
00:12:34:WU01:FS00:Cleaning up
```
Then, there's a 99.9% chance that the credit will eventually show up without issues sooner or later. During this time, the science being generated is still valid and one can continue to fold without waiting for stats if they choose to do so. You can generally see few reports if you check out the Official Forum: https://foldingforum.org/viewforum.php?f=35

Since this isn't an issue, I will close this now 😄

**Comment by NicoleRauch** [comment]
@PantherX  Thank you for your quick response! Thank you for pointing me to the WU Status Web App, I will use that from now on.

Unfortunately, the second WU I was reporting is this one:
https://apps.foldingathome.org/wu#project=16927&run=13&clone=920&gen=26
which (as you can see) cannot be found...
(Because of the download at 99% there is a crossover of the new download and the old upload, therefore the upload appears later than the download.)
The one after that went through fine again (no surprise to me as it is a shorter one again).

Do you still think it's not an issue, as it seems to have appeared twice already? ;-)

**Comment by NicoleRauch** [comment]
Here is the one from the day before that I already suspected. It also cannot be found:

https://apps.foldingathome.org/wu#project=16927&run=26&clone=898&gen=27
```
10:57:59:WU00:FS00:0xa7:*********************** Log Started 2020-12-30T10:57:59Z ***********************
10:57:59:WU00:FS00:0xa7:Project: 16927 (Run 26, Clone 898, Gen 27)
15:30:21:WU00:FS00:Sending unit results: id:00 state:SEND error:NO_ERROR project:16927 run:26 clone:898 gen:27 core:0xa7 unit:0x000003820000001b0000421f0000001a
```

---

These issues made me curious, and so I searched for all of my WUs in the WU Status Web App. Here are my findings:

---

The following WUs got attributed to a different user but not me, although they appear in my logfile:

https://apps.foldingathome.org/wu#project=16460&run=0&clone=1630&gen=55
```
08:31:56:WU00:FS00:0xa7:*********************** Log Started 2020-12-30T08:31:55Z ***********************
08:31:56:WU00:FS00:0xa7:Project: 16460 (Run 0, Clone 1630, Gen 55)
09:30:20:WU00:FS00:Sending unit results: id:00 state:SEND error:NO_ERROR project:16460 run:0 clone:1630 gen:55 core:0xa7 unit:0x0000065e000000370000404c00000000
```

https://apps.foldingathome.org/wu#project=16458&run=128&clone=1&gen=38
```
14:42:00:WU01:FS00:0xa7:*********************** Log Started 2020-12-26T14:41:59Z ***********************
14:42:00:WU01:FS00:0xa7:Project: 16458 (Run 128, Clone 1, Gen 38)
15:50:33:WU01:FS00:Sending unit results: id:01 state:SEND error:NO_ERROR project:16458 run:128 clone:1 gen:38 core:0xa7 unit:0x00000001000000260000404a00000080
```

https://apps.foldingathome.org/wu#project=16459&run=85&clone=2&gen=54
```
13:41:25:WU00:FS00:0xa7:*********************** Log Started 2020-12-26T13:41:25Z ***********************
13:41:25:WU00:FS00:0xa7:Project: 16459 (Run 85, Clone 2, Gen 54)
14:41:59:WU00:FS00:Sending unit results: id:00 state:SEND error:NO_ERROR project:16459 run:85 clone:2 gen:54 core:0xa7 unit:0x00000002000000360000404b00000055
```

https://apps.foldingathome.org/wu#project=16459&run=75&clone=0&gen=57
```
14:51:36:WU01:FS00:0xa7:*********************** Log Started 2020-12-25T14:51:36Z ***********************
14:51:36:WU01:FS00:0xa7:Project: 16459 (Run 75, Clone 0, Gen 57)
16:02:38:WU01:FS00:Sending unit results: id:01 state:SEND error:NO_ERROR project:16459 run:75 clone:0 gen:57 core:0xa7 unit:0x00000000000000390000404b0000004b
```

---

These WUs cannot be found altogether:

https://apps.foldingathome.org/wu#project=16461&run=79&clone=3&gen=72
```
15:11:25:WU01:FS00:0xa7:*********************** Log Started 2020-12-27T15:11:24Z ***********************
15:11:25:WU01:FS00:0xa7:Project: 16461 (Run 79, Clone 3, Gen 72)
16:28:23:WU01:FS00:Sending unit results: id:01 state:SEND error:NO_ERROR project:16461 run:79 clone:3 gen:72 core:0xa7 unit:0x00000003000000480000404d0000004f
```

https://apps.foldingathome.org/wu#project=16927&run=31&clone=151&gen=55
```
19:15:21:WU00:FS00:0xa7:*********************** Log Started 2020-12-26T19:15:21Z ***********************
19:15:21:WU00:FS00:0xa7:Project: 16927 (Run 31, Clone 151, Gen 55)
23:34:42:WU00:FS00:Sending unit results: id:00 state:SEND error:NO_ERROR project:16927 run:31 clone:151 gen:55 core:0xa7 unit:0x00000097000000370000421f0000001f
```

https://apps.foldingathome.org/wu#project=16462&run=142&clone=2&gen=39
```
12:09:33:WU01:FS00:0xa7:*********************** Log Started 2020-12-23T12:09:33Z ***********************
12:09:33:WU01:FS00:0xa7:Project: 16462 (Run 142, Clone 2, Gen 39)
13:09:15:WU01:FS00:Sending unit results: id:01 state:SEND error:NO_ERROR project:16462 run:142 clone:2 gen:39 core:0xa7 unit:0x00000002000000270000404e0000008e
```
Note: During the above WU run I switched the number of SMP threads, which caused some warnings, but then the WU was continued normally and finally uploaded.

https://apps.foldingathome.org/wu#project=16927&run=25&clone=173&gen=37
```
14:40:24:WU00:FS00:0xa7:*********************** Log Started 2020-12-17T14:40:24Z ***********************
14:40:24:WU00:FS00:0xa7:Project: 16927 (Run 25, Clone 173, Gen 37)
20:09:12:WU00:FS00:Sending unit results: id:00 state:SEND error:NO_ERROR project:16927 run:25 clone:173 gen:37 core:0xa7 unit:0x0000002a8120d1c900000000001900ad
```
During the above WU run there were also some interruptions, probably due to me switching the number of SMP threads.

---

If you need more information from my logfile, please get in touch with me and I'll be happy to submit it somewhere. Thanks for looking into this!

**Comment by PantherX** [comment]
> (Because of the download at 99% there is a crossover of the new download and the old upload, therefore the upload appears later than the download.)

Assuming you have a fast internet speed, you can configure the client to download the WU at 100% instead of 99% which would minimize the cross-over. You can do that by adding `<next-unit-percentage v='100'/>` to the Extra client options
![image](https://user-images.githubusercontent.com/5349122/103431186-328ad580-4c31-11eb-9028-6c62141b010b.png)

 
> Do you still think it's not an issue, as it seems to have appeared twice already? ;-)

Assuming that you mean that you're folding a WU that has already been folded without issues, then I would say that if it happens occasionally, then it's not an issue. It's an uncommon event which occurs due to human errors or technical issues.

----

Based on your reports this is the summary that I came up with:
Project ID | Project Owner | Server IP | Server Owner | Note
:--- | :--- | :--- | :--- | :--- | 
16927 | shahlo.solieva | 129.32.209.201 | voelz | Investigating
16460 | sukrit.singh | 128.252.203.11 | joseph | Notified
16458 | sukrit.singh | 128.252.203.11 | joseph | Notified
16459 | sukrit.singh | 128.252.203.11 | joseph | Notified
16461 | sukrit.singh | 128.252.203.11 | joseph | Notified
16462 | sukrit.singh | 128.252.203.11 | joseph | Notified

Hopefully, you can check them late next week and they will magically appear. If not, feel free to head to the Forum to create a thread or join an existing one if it exists 😄

**Comment by NicoleRauch** [comment]
> you can configure the client to download the WU at 100% instead of 99% which would minimize the cross-over

Oh, sorry, I just wanted to explain why you apparently looked at the wrong WU - you checked the downloaded one instead of the uploaded one, and I thought that might have happened because of the crossover. For me it's all good :-)

> Assuming that you mean that you're folding a WU that has already been folded without issues

No, that's perfectly fine and I understand why this happens.
I was referring to the (meanwhile) 11 WUs that cannot be found by the WU Stats Page (for my account) although I folded them. Given that my donor page attributes that I folded 135 WUs (which means that I folded 146 WUs altogether when also counting the lost ones), this is a loss rate of about 7.5% which I personally think is a high rate of losing WUs. I would probably call such a high loss rate an issue. But YMMV ;-)

Anyways, thank you very much for your prompt assistance, that's highly appreciated! Happy New Year 😃

**Comment by PantherX** [comment]
> Given that my donor page attributes that I folded 135 WUs (which means that I folded 146 WUs altogether when also counting the lost ones), this is a loss rate of about 7.5% which I personally think is a high rate of losing WUs. I would probably call such a high loss rate an issue. But YMMV ;-)

Ah, I see what you mean and get your POV. Please allow me to explain why this isn't considered a loss...

The system (Work Server) that Generates WUs that you are assigned is different than the system that credits the WU. Thus, as long as you have successfully uploaded the completed WU, there's no loss of science since the system would simply generate the next WU and carries on. From it's perspective, as long as it has received a successfully completed WU, it can generate the next one so science simply progresses happily.

The Stats system, goes around collecting the results of all process WUs (from the Work Servers) so that it can process them into the Database to present to us. Occasionally, the Stats system can't reach a particular Work Server or simply stops. In that case, what you see is this behavior where the WUs are successfully completed but doesn't "show" up in the Stats... yet. Generally, speaking, once we have notified the correct people, it tends to get resolved soon depending on availability.

What I was mentioning earlier was in reference where one WU successfully completed was processed by 2 or more donors. In F@H, we only aim to fold each WU once, thus all contributions are unique. There are some cases where a WU can be processed twice or more:
- If the first WU returned an error, two additional copies are sent out. Once a WU has received 5 errors, it is automatically stopped.
- If the first WU wasn't returned before the Timeout, a second copy will be assigned to ensure that science can progress.
- If the completed WU was uploaded to a secondary system (Collection Server) and there was a communication issue with the primary system (Work Server), the primary system wouldn't know that those WUs were returned so would assign them again.
- If a Project was "restarted" due to some technical bug (this only happens at the very start of the project and is uncommon).
- Some weird or obscure issue that rarely happens and is difficult to de-bug (#1532)


> Anyways, thank you very much for your prompt assistance, that's highly appreciated! Happy New Year 😃

Thanks 🤓 Wish you a wonderful New Year!

**Comment by jcoffland** [comment]
I looked into the original report in more detail.  It looks like the server in question ``vav18`` ran out of space on the partition holding the log files.  Although the WU results were not lost, this prevented it from logging the credits.  I'm working on some code changes to prevent this problem in the future.

**Comment by PantherX** [comment]
@jcoffland thanks for that! Is it fair to say that the issue that was identified on Server `vav18.fah.temple.edu` is the same as the one on `highland1.engr.wustl.edu` the two servers that were identified in this issue?

**Comment by jcoffland** [comment]
I think the credits on highland1 (128.252.203.11) were just delayed.  For example:  https://apps.foldingathome.org/wu#project=16462&run=142&clone=2&gen=39

**Comment by PantherX** [comment]
Awesome! Appreciate the prompt response 😃

**Comment by jcoffland** [comment]
Let me know if any of the highland1 WUs are still missing credits.

**Comment by PantherX** [comment]
Have just checked and all 6 WUs from Project 164XX (`highland1.engr.wustl.edu`) have been successfully credited to `NicoleR`:

- https://apps.foldingathome.org/wu#project=16460&run=0&clone=1630&gen=55
- https://apps.foldingathome.org/wu#project=16458&run=128&clone=1&gen=38
- https://apps.foldingathome.org/wu#project=16459&run=85&clone=2&gen=54
- https://apps.foldingathome.org/wu#project=16459&run=75&clone=0&gen=57
- https://apps.foldingathome.org/wu#project=16461&run=79&clone=3&gen=72
- https://apps.foldingathome.org/wu#project=16462&run=142&clone=2&gen=39

**Comment by NicoleRauch** [comment]
@PantherX Thank you very much for the detailed insights! I'm glad to hear that the science is not lost even if the points don't appear or are delayed.

@jcoffland Thank you for looking into this issue! Happy to hear that you were able to identify an underlying cause that can be addressed.

**Comment by jcoffland** [comment]
No problem.  Thanks for the report and let us know if you find any other problems.
