### ISSUE TITLE
Is it planned to add ROCm support ?

### ISSUE THREAD

**Issue by mauvray** [FoldingAtHome/fah-issues#1614]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Is your feature request related to a problem?

----
## Describe the Feature

My question is the title. More precisely, is it possible to add ROCm support like there is CUDA support ?

----
## Context

**My specs:**
GPU : rx vega 56
OS : fedora 33
OpenCL version : mesa, rocm

*A little bit of history.*
Before going to fedora 33, I was on Archlinux, with mesa and rocm. At that time, I could fold on my GPU thanks to OpenCL, but I could not get deep learning working. Because ROCm has official support for RHEL distrib I changed to Fedora 33. So I installed Fedora, ROCm (including ROCm-opencl), and deep learning works fine. `clinfo` even gives me that the two versions are detected correctly, then I installed foldingathome, I launched the daemon, then I checked the logs and I see that I have no support for openCL 1.2+. Knowing that the mesa version is only 1.1, I guess the problem comes from loading the rocm version, that provides openCL 2.0.  What I could find was that Fedora 33 seems to be a little bit messy with openCL.

Knowing that amd provides a tool to transpile CUDA to C++ code, is it possible/do you plan to distribute a version that could execute on ROCm ?

----

**Comment by PantherX** [comment]
I will ask around and see what happens 😄

**Comment by mauvray** [comment]
Just a little question, why did you put debian in the labels ? Does the same issue happen on it ?

**Comment by PantherX** [comment]
@mauvray I added Debian since I assumed that it was a Linux issue so applied both labels to it. Happy to update it if you want me to remove it.

BTW, ROMc OpenCL is supported and donors have been able to fold WUs without issues for few months. I would suggest that you hop on to our [Official Forum](https://foldingforum.org/index.php) and post the details there so someone who's experienced in Linux and ROCm can help you out 😄 


However, if you're thinking about HIP, then it isn't currently supported yet. You can read the discussion here if needed: https://github.com/openmm/openmm/pull/2736

**Comment by mauvray** [comment]
I tihnk it may be fedora specific since I was able to run it with rocm when my workstation was on arch, and my laptop can also fold on its amd gpu using rocm-opencl, and I red and asked a bit around (not on fah forums though) and it seemed that it is a little buggy to get amd opencl fedora 33. I will ask on folding at home forums and thank you for the links :)

**Comment by PantherX** [comment]
Thanks for that! I have updated the labels and will close this issue for now. However, if at the Folding Forum it is discovered to be a bug, it can easily be re-opened with any additional details (if needed) 😄
